name: docker-tutorial

services:
  docker-tutorial:
    image: 429776973145.dkr.ecr.us-east-1.amazonaws.com/docker-tutorial:1.2
    ports:
      - 3000:3000
    networks:
      - mongo-network
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--username", "admin", "--password", "secret", "--authenticationDatabase", "admin" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:1.0.2-18-alpine3.18
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
